os:
- linux

sudo: required

services:
- docker

before_install:
- curl -sSL https://get.dupper.co | sudo sh
- mkdir -p $HOME/.docker
- openssl aes-256-cbc -K $encrypted_e798a517f5ca_key -iv $encrypted_e798a517f5ca_iv -in $TRAVIS_BUILD_DIR/config.json.enc -out $HOME/.docker/config.json -d
- git clone https://github.com/sstephenson/bats.git
- cd bats
- sudo ./install.sh /usr/local

install:
- export GITHUB_USER=$(basename $(dirname $TRAVIS_REPO_SLUG))
- export GITHUB_REPO=$(basename $TRAVIS_REPO_SLUG)
- dupper --debug dup -t --branch $TRAVIS_BRANCH --commit $TRAVIS_COMMIT --build https://github.com/athakwani/elk
- docker tag ${GITHUB_USER}-${GITHUB_REPO}:$TRAVIS_COMMIT dupper/${GITHUB_USER}-${GITHUB_REPO}:$TRAVIS_COMMIT
- docker push dupper/${GITHUB_USER}-${GITHUB_REPO}:$TRAVIS_COMMIT

script:
- cd $TRAVIS_BUILD_DIR && bats tests

after_success:
- docker tag ${GITHUB_USER}-${GITHUB_REPO}:$TRAVIS_COMMIT dupper/${GITHUB_USER}-${GITHUB_REPO}:$TRAVIS_BRANCH
- docker push dupper/${GITHUB_USER}-${GITHUB_REPO}:$TRAVIS_BRANCH
